#!/usr/bin/env bash
set -euo pipefail

# ---------------------------------------------------------------------------
# setup.sh — Interactive first-time configuration for this template
#
# What it does:
#   1. Prompts for app name, GitHub org/repo, AWS account/region, domain
#   2. Writes values into cdk/config/environments.ts and cdk/app.ts
#   3. Writes ANTHROPIC_API_KEY (and optionally Turnstile keys) to .env.local
#   4. Updates package.json name field
#
# Run once after cloning:  bash setup.sh
# ---------------------------------------------------------------------------

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; CYAN='\033[0;36m'; NC='\033[0m'

info()    { echo -e "${CYAN}$*${NC}"; }
success() { echo -e "${GREEN}✓ $*${NC}"; }
warn()    { echo -e "${YELLOW}⚠ $*${NC}"; }
error()   { echo -e "${RED}✗ $*${NC}"; exit 1; }

prompt() {
  local label="$1" default="${2:-}" var
  if [[ -n "$default" ]]; then
    read -rp "$(echo -e "${CYAN}${label}${NC} [${default}]: ")" var
    echo "${var:-$default}"
  else
    read -rp "$(echo -e "${CYAN}${label}${NC}: ")" var
    echo "$var"
  fi
}

prompt_secret() {
  local label="$1" var
  read -rsp "$(echo -e "${CYAN}${label}${NC}: ")" var
  echo ""  >&2
  echo "$var"
}

confirm() {
  local label="$1" default="${2:-y}" answer
  read -rp "$(echo -e "${CYAN}${label}${NC} [${default}]: ")" answer
  answer="${answer:-$default}"
  [[ "$answer" =~ ^[Yy] ]]
}

# ---- Check we're in the right directory ------------------------------------

[[ -f "cdk/app.ts" && -f "cdk/config/environments.ts" ]] \
  || error "Run this script from the project root (same directory as cdk/)"

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  React Router on AWS Lambda — Initial Setup"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
info "This script configures cdk/app.ts, cdk/config/environments.ts,"
info "package.json, and writes your API keys to .env.local."
echo ""

# ---- Gather input ----------------------------------------------------------

APP_NAME=$(prompt "App name (used as CDK stack prefix, no spaces)" "my-app")
AWS_ACCOUNT=$(prompt "AWS account ID (12 digits)")
AWS_REGION=$(prompt "AWS region" "us-east-1")

echo ""
info "GitHub details (used for OIDC-based CI/CD — no stored credentials):"
GITHUB_ORG=$(prompt "GitHub org or username")
GITHUB_REPO=$(prompt "GitHub repository name")

echo ""
if confirm "Do you have a custom domain to configure?"; then
  DOMAIN=$(prompt "Custom domain (e.g. myapp.example.com)")
else
  DOMAIN=""
fi

echo ""
info "API keys (written to .env.local — never committed):"
ANTHROPIC_KEY=$(prompt_secret "Anthropic API key")

echo ""
if confirm "Configure Cloudflare Turnstile bot protection? (optional)"; then
  TURNSTILE_SITE=$(prompt "Turnstile site key")
  TURNSTILE_SECRET=$(prompt_secret "Turnstile secret key")
else
  TURNSTILE_SITE=""
  TURNSTILE_SECRET=""
fi

# ---- Validate --------------------------------------------------------------

[[ "$AWS_ACCOUNT" =~ ^[0-9]{12}$ ]] \
  || error "AWS account ID must be exactly 12 digits. Got: $AWS_ACCOUNT"

[[ -n "$APP_NAME" ]] || error "App name cannot be empty"
[[ -n "$GITHUB_ORG" ]] || error "GitHub org cannot be empty"
[[ -n "$GITHUB_REPO" ]] || error "GitHub repo cannot be empty"
[[ -n "$ANTHROPIC_KEY" ]] || error "Anthropic API key cannot be empty"

echo ""
info "Summary:"
echo "  App name:      $APP_NAME"
echo "  AWS account:   $AWS_ACCOUNT"
echo "  AWS region:    $AWS_REGION"
echo "  GitHub:        $GITHUB_ORG/$GITHUB_REPO"
echo "  Custom domain: ${DOMAIN:-none}"
echo ""

confirm "Apply these settings?" || { echo "Aborted."; exit 0; }

# ---- Write cdk/config/environments.ts -------------------------------------

DOMAIN_LINE=""
if [[ -n "$DOMAIN" ]]; then
  DOMAIN_LINE="    domainName: \"${DOMAIN}\","
fi

cat > cdk/config/environments.ts << TSEOF
/**
 * Per-Environment Configuration for CDK Deployments
 *
 * Generated by setup.sh — edit manually if you need to change settings.
 */

import * as logs from "aws-cdk-lib/aws-logs";

export enum Stage {
  prod = "prod",
}

export interface EnvironmentConfig {
  /** Environment stage name */
  stage: Stage;
  /** AWS Account ID */
  accountId: string;
  /** AWS Region */
  region: string;
  /** Lambda memory in MB */
  lambdaMemory: number;
  /** CloudWatch Logs retention */
  logRetention: logs.RetentionDays;
  /** CloudFront HTML cache TTL in minutes */
  htmlCacheTtlMinutes: number;
  /** CloudFront assets cache TTL in days */
  assetsCacheTtlDays: number;
  /** Custom domain name (optional) */
  domainName?: string;
}

const environments: Record<Stage, EnvironmentConfig> = {
  [Stage.prod]: {
    stage: Stage.prod,
    accountId: "${AWS_ACCOUNT}",
    region: "${AWS_REGION}",
    lambdaMemory: 1024,
    logRetention: logs.RetentionDays.ONE_MONTH,
    htmlCacheTtlMinutes: 60,
    assetsCacheTtlDays: 30,
${DOMAIN_LINE}
  },
};

export function getEnvironmentConfig(stage: string): EnvironmentConfig {
  if (stage !== "prod") {
    throw new Error(\`Invalid stage "\${stage}". Must be "prod".\`);
  }
  const config = environments[stage as Stage];
  if (!config) {
    throw new Error(\`Production configuration not found for stage: \${stage}\`);
  }
  return config;
}

export function getAllEnvironments(): Record<Stage, EnvironmentConfig> {
  return environments;
}

export default getEnvironmentConfig;
TSEOF

success "cdk/config/environments.ts updated"

# ---- Write cdk/app.ts ------------------------------------------------------

# Replace the three config constants regardless of current value
node -e "
const fs = require('fs');
let content = fs.readFileSync('cdk/app.ts', 'utf8');
content = content
  .replace(/const GITHUB_ORG = \"[^\"]*\";/, 'const GITHUB_ORG = \"${GITHUB_ORG}\";')
  .replace(/const GITHUB_REPO = \"[^\"]*\";/, 'const GITHUB_REPO = \"${GITHUB_REPO}\";')
  .replace(/const APP_NAME = \"[^\"]*\";/, 'const APP_NAME = \"${APP_NAME}\";');
fs.writeFileSync('cdk/app.ts', content);
"
success "cdk/app.ts updated"

# ---- Update package.json name ----------------------------------------------

# Use node to do a safe JSON edit
node -e "
const fs = require('fs');
const pkg = JSON.parse(fs.readFileSync('package.json', 'utf8'));
pkg.name = '${APP_NAME}';
fs.writeFileSync('package.json', JSON.stringify(pkg, null, 2) + '\n');
"
success "package.json name updated"

# ---- Write .env.local ------------------------------------------------------

ENV_FILE=".env.local"

# Build env file contents
ENV_CONTENT="# Generated by setup.sh — do not commit this file
ANTHROPIC_API_KEY=${ANTHROPIC_KEY}
"

if [[ -n "$TURNSTILE_SITE" ]]; then
  ENV_CONTENT+="TURNSTILE_SITE_KEY=${TURNSTILE_SITE}
TURNSTILE_SECRET_KEY=${TURNSTILE_SECRET}
"
fi

echo "$ENV_CONTENT" > "$ENV_FILE"

# Ensure .env.local is gitignored
if ! grep -q "^\.env\.local$" .gitignore 2>/dev/null; then
  echo ".env.local" >> .gitignore
  success ".env.local added to .gitignore"
fi

success ".env.local written"

# ---- Done ------------------------------------------------------------------

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
success "Setup complete!"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Next steps:"
echo ""
echo "  1. Install dependencies:"
echo "     npm install"
echo ""
echo "  2. Customize the AI assistant (optional):"
echo "     • src/app/lib/agent/system-prompt.ts — Claude's behavior"
echo "     • src/app/features/welcome/constants.ts — welcome message & suggestions"
echo ""
echo "  3. Build and deploy:"
echo "     npm run release"
if [[ -n "$DOMAIN" ]]; then
  echo ""
  echo "  4. First deploy the DNS stack, then copy nameservers to your registrar:"
  echo "     npx cdk deploy ${APP_NAME}-dns-prod"
  echo "     (then point your domain to the nameservers shown in the output)"
  echo ""
  echo "  5. Deploy all remaining stacks:"
  echo "     npx cdk deploy --all"
else
  echo "     npx cdk deploy --all"
fi
echo ""
if [[ -n "$DOMAIN" ]]; then
  echo "  Your app will be available at: https://${DOMAIN}"
else
  echo "  Your app URL will be shown in the CloudFront output after deploy."
fi
echo ""
warn "ANTHROPIC_API_KEY is written to .env.local and loaded into Lambda env"
warn "at CDK deploy time. Rotate the key if it is ever exposed."
echo ""
